### ISSUE TITLE
404 not found

### ISSUE THREAD

**Issue by lcerrato** [ThomasK81/LightWeightCTSServer#1]
The example link (4)
http://localhost:8080/cts/range/tlg0085.tlg005.opp-grc3/1@τῶνδ᾽-12@ἂν

returns a 404 error.

All of the other examples work.

**Comment by ThomasK81** [comment]
Thank you. Fixed the link in the description. It had to be:
http://localhost:8080/cts/range/tlg0085.tlg005.opp-grc3:1@τῶνδ᾽-12@ἂν
